destination: ../site
logo: NAUT
name: nautkoncept.se
description: Konceptutveckling AB
url: http://nautkoncept.se
permalink: /:title/
paginate: 12
paginate_path: /page/:num/
tag_dir: /tag
media_folder: /img
tumblr:
pinterest:
instagram:
twitter: "#"
facebook: "#"
youtube:
vimeo:
soundcloud:

port: 9797
gems: [jekyll-paginate]

encoding: utf-8
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      type: "standard"
      homedisplay: "featimg"
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
relative_permalinks: false
exclude: [.git, .gitignore, sass, .sass-cache, package.json, gruntfile.js, node_modules, README.md, documentation]

# prose.io configurations
prose:
  rooturl: ''
  siteurl: 'http://nautkoncept.se/'
  relativeLinks: 'http://nautkoncept.se/links.jsonp'
  ignore:
    - index.html
    - _config.yml
    - /_layouts
    - /_includes
    - _data
    - _plugins
    - _site
    - archive
    - about
    - case
    - education 
    - css
    - fonts
    - img
    - js
    - page
    - project
    - sass
    - typography
    - 404.html
    - CNAME
    - feed.xml
    - file_name_and_front_matter_generator.html
  metadata:
    _posts:
      - name: "category"
        field:
          element: "multiselect"
          label: "Kategori"
          placeholder: "V채lj kategorier"
          options:
            - name: "Case"
              value: "case"
            - name: "Education"
              value: "edu"
            - name: "Video p책 framsida"
              value: "pinned-video"
            - name: "Post p책 framsida"
              value: "pinned-post"
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicerad"
          value: "true"
      - name: "title"
        field:
          element: "text"
          type: "text"
      - name: "date"
        field:
          element: "hidden"
          value: CURRENT_DATETIME
      - name: "layout"
        field:
          element: "hidden"
          value: post_full
      - name: "vimeo-embed"
        field:
          element: "text"
          label: "Vimeo Embedding Code"
          help: "Klistra in allt mellan &lt;iframe&gt;...&lt;/iframe&gt;."
      - name: "yt-video-id"
        field:
          element: "text"
          label: "Youtube ID"
          help: "youtube id finner du i adressf채ltet efter v="
